### ISSUE TITLE
Assertions for headers

### ISSUE THREAD

**Issue by jimmypuckett** [spinen/laravel-mail-assertions#6]
Check for specific email headers & values of the headers

**Comment by ssfinney** [comment]
The header methods are here: https://github.com/swiftmailer/swiftmailer/blob/5.x/lib/classes/Swift/Mime/HeaderSet.php

Just use "getHeaders()" to get them, then use the methods above (like maybe getAll) to grab and parse them.

Maybe make a method called `seeEmailHeaderContains($header, $value)`

**Comment by ssfinney** [comment]
@jimmypuckett So as it turns out, all the headers have their own getter methods in the SwiftMailer. There's no need for a custom method to find a specific header value. We can just wrap each of those header methods with an assertion.

Most of these are already an issue in this project (like checking for the date, or the subject, or the cc address, etc.) So I'm closing this and opening a few new ones.
